### ISSUE TITLE
Transparent images displaying with a background

### ISSUE THREAD

**Issue by jerdog** [gitpitch/gitpitch#183]
Image: https://github.com/jerdog/droidconde18/blob/master/assets/image/auth0-logo-transparent.png
Slide: https://gitpitch.com/jerdog/droidconde18#/16

As you can tell the image is transparent but is displaying with a gray background different from the theme.

**Comment by gitpitch** [comment]
Hi Jeremy, you have activated the *night* theme for your presentation. If you inspect the default CSS rules for your image under this theme you will see the following rules are active:

```css
.reveal section img {
    margin: 15px 0px;
    background: rgba(255, 255, 255, 0.12);
    border: 4px solid #eee;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
}
```
 
Note in particular the value defined for the *background* property.

If you want to override the defaults for your chosen theme you will need to activate a little bit of [custom css](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS).

Specifically, your custom css should probably end up looking something like this:

```
.reveal section img {
    background: none !important;
    box-shadow: none !important;
}
```
