### ISSUE TITLE
Logo-Size

### ISSUE THREAD

**Issue by kenrim626** [gitpitch/gitpitch#185]
A logo with the dimensions of 600x492 pixels gets resized to a very small image. 
If possible, I would like it to be a bit larger. Is it possible to change the logo size?

I already tried to set the size property in the `PITCHME.yaml`:
`logo : ./assets/images/logo.png?size=30% auto`

**Comment by gitpitch** [comment]
> Is it possible to change the logo size?

Yes, you can activate your own [custom css](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS) to target the `logo` and size it any way you want. For further information, see #53. Keep in mind your presentation may be viewed on devices with widely divergent resolutions - so using fixed pixel sizes is generally not recommended.

**Comment by kenrim626** [comment]
After fiddling with it for a bit I found out that I had to disable the `max-height` and `max-width` properties for decent results, but now it works like a charm! Thanks for the quick response!

```css
#gp-logo {
    width: 15%;
    height: auto;
}

#gp-logo img {
    width: 100%;
    height: 100%;
    max-height: none;
    max-width: none;
}
```
