### ISSUE TITLE
Ability to include PITCHME.yaml files

### ISSUE THREAD

**Issue by satano** [gitpitch/gitpitch#277]
It would be nice to have an ability to include another `PITCHME.yaml` in `PITCHME.yaml`.

## Implementation

Just use simple `include` key with path to another `PITCHME.yaml`. For simplicity and consistency with other features, the path is relative to the repository root: `include: PITCHME.yaml`

## Reasoning

Some settings in `PITCHME.yaml` can be specific for presentations, som other settings can be global.

For example there will be _master_ `PITCHME.yaml` in the root of the repository, where will be specified colors, fonts, code highlighting style, custom CSS etc. In general there would be global design/theme settings.

And there will be another `PITCHME.yaml` next to the presentation itself (next to `PITCHME.md`). In this `yaml` file, we can just include the master `yaml` and add/update other setting. For example:

``` yml
include: PITCHME.yaml # Global settings for all my presentsations.

# Every presentation has its own title.
title: My Super Presentation

# I want different logos for different presentations, or maybe I do not want any logo in some.
logo: https://example.com/path/to/logo.png
```

## Things to consider

- Depth of including. Again for simplicity, I believe that it is enough to support just one level of include (the same as including `PITCHME.md` files). So included `PITCHME.yaml` cannot contain `include` key.
- In general, I think that mostly the `include` will be at the begining of the file. But i should be clear the behavior if the include is somewher _in the middle_. Possibilities:
  - Force the `include` (if present) to be the first key in `.yaml`. Show error if it is not the case.
  - Allow `include` to be anywhere, but always process it first. So local settings will always override global settings, even if they are before the `include`.
  - Allow `include` to be anywhere and process the files from top to bottom. So process settings in local file, then include global file and process that - it may override already set settings. Then process the rest of local file, which will override any previous settings. This is probably the expected behavior.
