### ISSUE TITLE
YAML Syntax Highlighting Confused with Hash Value

### ISSUE THREAD

**Issue by AdamSmith89** [gitpitch/gitpitch#285]
I have a YAML file which has a value that contains numbers and letters. The value isn't surrounded by quotes.

As shown below the syntax highlighting is creating two `span`s for the one value, a number span followed by a string span.
![gitpitch_syntax_issue](https://user-images.githubusercontent.com/24701281/73257781-48d81800-41bc-11ea-903f-65a00dffc8af.png)

Is there anyway to override this behaviour or get it to treat the value as a single type? I'm currently not using the pro edition so it might be possible with the `@code` widget?

_Note, I've since removed the value entirely from the presentation but thought I'd bring this to your attention._

**Comment by gitpitch** [comment]
Hi Adam, thanks for bringing this to my attention. Can you share the exact YAML snippet you were using with me here as a code block so I can copy and paste it for local testing. Thanks, David.

**Comment by AdamSmith89** [comment]
Sure thing, and thanks for the quick reply.

```yaml
# Defined in seconds
globalScrapeTime: 120
listenOnPort: 9091
sonarqubeUrl: https://someurl.com
sonarqubeUser: serviceaccount
sonarqubePassword: 849176324b1ad53ccd5dc67072a79dd92fbb6df7

**Comment by gitpitch** [comment]
Ok. So I just dropped your sample YAML code block into GitPitch Desktop and this is what I see:

![yaml-code-block](https://user-images.githubusercontent.com/19169584/73270217-d180a380-4210-11ea-9248-9252f6693136.png)

That looks good to me. So I would have to see exactly what you were doing and how you were doing it to understand why your slide rendered the way it did. How were you testing this? If you can recreate the issue and share a link to a sample deck I'll be happy to take a look.

**Comment by AdamSmith89** [comment]
That looks the same as my screenshot? The issue is the `Password` value being multi-coloured; the first 9 characters purple and the rest are green. I'd expect the whole value to be treated as a string, and therefore all be coloured green.

**Comment by gitpitch** [comment]
When I  looked at your screenshot I assumed the problem you were reporting was the weird tabbing of your YAML entries and the missing text on the URL. I see now that there is indeed one additional issue, the color highlighting on the password text.

Th ere are two solutions to this:

1. Make the password an explicit string using quotes. That remains valid YAML and will also ensure that the entire string is rendered as as string, not a number followed by a string. And to be crystal clear, I mean like this:

```yaml
# Defined in seconds
globalScrapeTime: 120
listenOnPort: 9091
Url: https://someurl.com
User: serviceaccount
Password: "849176324b1ad53ccd5dc67072a79dd92fbb6df7"
```

2. Assuming this password is for demonstration purposes only - is to start the password string with any non-digit character, such as:

```yaml
# Defined in seconds
globalScrapeTime: 120
listenOnPort: 9091
Url: https://someurl.com
User: serviceaccount
Password:  a849176324b1ad53ccd5dc67072a79dd92fbb6df7
```
