### ISSUE TITLE
docker gitpitch/desktop:pro hangs on local repo directory

### ISSUE THREAD

**Issue by graphadvantage** [gitpitch/gitpitch#291]
Hi 

It seems the docker container startup is hanging when I point to my local GitHub repo directory.

```
(base) USC02ZX15JMD6R:gitpitch-docker Michael.Moore4@ey.com$ docker-compose up
Recreating gitpitch-docker_gitpitch_1 ... done
Attaching to gitpitch-docker_gitpitch_1
gitpitch_1  | 2020-03-10 18:59:10,855 [info] c.g.s.DesktopService - GitPitch Desktop Pro Edition started.

[hangs here]

```

If I point to a project inside the repo directory with a PITCHME.md then it starts up and finishes the file sweep, but of course doesn't show any other repos with PITCHME.md files.

```
(base) USC02ZX15JMD6R:gitpitch-docker Michael.Moore4@ey.com$ docker-compose up
Recreating gitpitch-docker_gitpitch_1 ... done
Attaching to gitpitch-docker_gitpitch_1
gitpitch_1  | 2020-03-10 19:11:51,012 [info] c.g.s.DesktopService - GitPitch Desktop Pro Edition started.
gitpitch_1  | 2020-03-10 19:11:51,225 [info] c.g.s.RefreshService - SWEEP directory watcher detected 65 files in 170 ms.
gitpitch_1  | 2020-03-10 19:11:51,227 [info] c.g.s.RefreshService - SWEEP directory watcher using default interval 250 ms.
gitpitch_1  | 2020-03-10 19:11:51,903 [info] play.api.Play - Application started (Prod)
gitpitch_1  | 2020-03-10 19:11:52,094 [info] p.c.s.NettyServer - Listening for HTTP on /0.0.0.0:9000
```

here is the docker-compose file

```
services:
  gitpitch:
    image: gitpitch/desktop:pro
    volumes:
      - /Users/Michael.Moore4@ey.com/Documents/GitHub:/repo
    ports:
      - "9000:9000"
    environment:
      - PORT=9000

```
is this the expected behavior?
